### ISSUE TITLE
TrAELseq_preprocessing

### ISSUE THREAD

**Issue by sagarutturkar** [FelixKrueger/Umi-Grinder#3]
Hello,

Thanks for providing this nice toolkit for TrAEL-seq. We have the new TrAEL-seq data and I am getting an error while running the tool. 

I tried the very first step:  `TrAELseq_preprocessing.py` and I get the error below:

```
Python version: 3.6.8 (default, Apr  2 2020, 13:34:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)].
Reading in FastQ file:   >> SRR12279038.fastq.gz <<

Reading file: >SRR12279038.fastq.gz<
Got following sample name: UMIed
SRR12279038.fastq.gz
Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/TrAEL-seq-31-aug-2022/TrAELseq_preprocessing.py", line 147, in <module>
    submain()
  File "/group/bioinfo/apps/apps/TrAEL-seq-31-aug-2022/TrAELseq_preprocessing.py", line 32, in submain
    main(filename)
  File "/group/bioinfo/apps/apps/TrAEL-seq-31-aug-2022/TrAELseq_preprocessing.py", line 43, in main
    outfh = make_out_filehandle("UMIed",filename)
  File "/group/bioinfo/apps/apps/TrAEL-seq-31-aug-2022/TrAELseq_preprocessing.py", line 133, in make_out_fileh
    sample = m[0][0]
IndexError: list index out of range
```

Note that I get the same error with my own data or  TrAEL-seq data from the SRA. 

The SRA data has re-formatted the header information and I am not sure if read-headers should have a specific format:

$zcat SRR13358270.fastq.gz | head

```

@SRR13358270.1 NB501547:439:H2GVCBGXG:1:11101:19590:1038 length=66
AGGGGGACCGAACCCCGAAGGAGTGCGGGACCCCGTGGGAACCGCATCCCTTTTTATTTTTAATTA
+SRR13358270.1 NB501547:439:H2GVCBGXG:1:11101:19590:1038 length=66
EEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEAEEEEEEEEEEEEEEEE
@SRR13358270.2 NB501547:439:H2GVCBGXG:1:11101:2895:1038 length=65
ATACTCAACGCTTTTCTTTTTCTTCTTTTTCTTTCCATCCTAATCATGCGCGCAATAGGAAAGCG
+SRR13358270.2 NB501547:439:H2GVCBGXG:1:11101:2895:1038 length=65
EEEE/AEAAA/AE/EAEEEEEE/EEAE/EEEEEEE<EEEA<EE6EE//AEA<EEA/A//EEEE/A
@SRR13358270.3 NB501547:439:H2GVCBGXG:1:11101:7282:1040 length=65
TCTGGGGCCACGGAAGCCGGAACCCCGTAAGGAGAAATATACATATAGATAATAAATCTTTAAGA

```

My own data looks like below:

```
@NB501714:136:HM3F7AFX3:1:11101:21409:1049 1:N:0:GTTTCG
NCTCCCCCTCGATCTCTATACCTTTTTAGCCGCCCATCTTCTGCCTTTCATTTTTATGCCAACCCTCCATCCATA
+
#AAAAEEEEEEEEEEEEEAEEAEEEE/EEAAEAEEEEEEEEEEEEE/EEEE/E<AEE/EEAEAEA<EEEE<EEAE
@NB501714:136:HM3F7AFX3:1:11101:11170:1049 1:N:0:GTTTCG
NCTTACCTTAAATTTCGTCACACTATCAAAGTGAACAAAGCACAGAATGTGTTTGCTACTCAATCATGTTCAAGT
+
#AAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEE/EAEEEEEEEEEEAEEAAEEEEEEEEEEEE
@NB501714:136:HM3F7AFX3:1:11101:14121:1049 1:N:0:GTTTCG
NACACAATTTTATCATGAAATTGAGTAATGTGTGGTTTCAGTGTTTAAAACTGGACGATCAAATTGTGTCACAAT


```

**Do you have any suggestions to make this work?**

**Comment by FelixKrueger** [comment]
Apologies for the late reply, I have just returned from holidays. I think the issue is only caused because the filenames you are providing are structured differently to what the script expects. 

You should be able to change the regular expression for this in the script  (line: https://github.com/FelixKrueger/TrAEL-seq/blob/575f2add23ab380247164e9d0b0e91d2357ef525/TrAELseq_preprocessing.py#L129)

from 
```python
pattern = '(lane.*_L00\d)_(R\d.fastq.gz)'
```

to: 
```python
pattern = '(.*)(.fastq.gz)'
```

You might want to rename the files afterwards as they will have *_UMIed_.fastq.gz in their new filenames, but this is really cosmetic. The command would be (in most linux installations):

```
rename _. . *
```

**Comment by sagarutturkar** [comment]
Thank you for the quick response. This resolved my query. 
Thank you again for providing such a nice toolkit.

**Comment by FelixKrueger** [comment]
excellent!
